using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Common.Enums
{
    public enum BrandType
    {
        Acura,
        Alfa_Romeo,
        Aston_Martin,
        Audi,
        Bentley,
        BMW,
        Bugatti,
        Buick,
        Cadillac,
        Chevrolet,
        Chrysler,
        Citroën,
        Dacia,
        Daewoo,
        Daihatsu,
        Dodge,
        Ferrari,
        Fiat,
        Ford,
        Geely,
        Genesis,
        GMC,
        Honda,
        Hyundai,
        Hummer,
        Infiniti,
        Isuzu,
        Iveco,
        Jaguar,
        Jeep,
        Kia,
        Lamborghini,
        Lancia,
        Land_Rover,
        Lexus,
        Lincoln,
        Lotus,
        Maserati,
        Mazda,
        McLaren,
        Mercedes_Benz,
        Mini,
        Mitsubishi,
        Nissan,
        Opel,
        Peugeot,
        Polestar,
        Porsche,
        RAM,
        Renault,
        Rolls_Royce,
        Saab,
        Seat,
        Škoda,
        Smart,
        Subaru,
        Suzuki,
        Tata,
        Tesla,
        Toyota,
        Volkswagen,
        Volvo,
        Zotye
    }
}
